### ISSUE TITLE
4.0-dev

### ISSUE THREAD

**Issue by dominikzogg** [chubbyphp/chubbyphp-serialization#25]
Hi @healerz @marko-ilic

I working on official PHP 8.3 support of my libraries. For this one i took the change to get rid of the deprecations. Would be great if you could test it with 4.0@dev if you're still using it.

Best

**Comment by komando82** [comment]
Apart from related [comment](https://github.com/chubbyphp/chubbyphp-deserialization/issues/45#issuecomment-1866254215) looks ok to me @dominikzogg @marko-ilic

**Comment by komando82** [comment]
Thank you. You can close this issue IMO.

**Comment by dominikzogg** [comment]
@komando82 @komando82 @healerz thx
